server {
    listen 80;
    server_name _;

    # Place this repo at /var/www/php-auth-app
    # URLs required by assignment:
    # - /admin/newuser.php
    # - /socialnet/signin.php, /socialnet/index.php, ...
    root /var/www/php-auth-app;
    index index.php;

    client_max_body_size 10m;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;

        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }
}

